import fs from 'fs';
import path from 'path';

const DFLOW_PM_BASE_URL = process.env.DFLOW_PM_BASE_URL!;

export type DflowStockConfig = {
  mint: string;
  symbol: string;
  name: string;
  /** Optional CoinGecko coin ID (API ID), e.g. "amazon-xstock" */
  coingeckoId?: string;
  decimals?: number;
};

/**
 * Load curated Dflow-supported stocks from a local JSON file.
 * This file is generated by the sync-dflow-stocks script.
 */
export function loadDflowStocks(): DflowStockConfig[] {
  try {
    const p = path.join(process.cwd(), 'lib', 'dflow-stocks.json');
    const raw = fs.readFileSync(p, 'utf8');
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed as DflowStockConfig[];
    }
  } catch {
    // If file is missing or invalid, fall through to empty list.
  }
  return [];
}

// Re-export base URLs for other Kalshi / trading integrations later.
export const DFLOW_BASES = {
  predictionMarkets: DFLOW_PM_BASE_URL,
};

